-- PUBLIC.DICTIONARY definition

-- Drop table

DROP TABLE IF EXISTS PUBLIC.DICTIONARY;
CREATE TABLE PUBLIC.DICTIONARY (
	ID INTEGER NOT NULL AUTO_INCREMENT,
	ENGLISH_WORD CHARACTER VARYING(255),
	CROATIAN_WORD CHARACTER VARYING(255),
	CONSTRAINT CONSTRAINT_3 PRIMARY KEY (ID)
);
CREATE UNIQUE INDEX PRIMARY_KEY_3 ON PUBLIC.DICTIONARY (ID);


-- PUBLIC.FLASHCARDS definition

-- Drop table

DROP TABLE IF EXISTS PUBLIC.FLASHCARDS;
CREATE TABLE PUBLIC.FLASHCARDS (
	ID INTEGER NOT NULL AUTO_INCREMENT,
	FRONT_TEXT CHARACTER VARYING(255),
	BACK_TEXT CHARACTER VARYING(255),
	CONSTRAINT CONSTRAINT_D PRIMARY KEY (ID)
);
CREATE UNIQUE INDEX PRIMARY_KEY_D ON PUBLIC.FLASHCARDS (ID);


-- PUBLIC.QUIZ definition

-- Drop table

DROP TABLE IF EXISTS PUBLIC.QUIZ;
CREATE TABLE PUBLIC.QUIZ (
	ID INTEGER NOT NULL AUTO_INCREMENT,
	QUESTION CHARACTER VARYING(255),
	OPTION_1 CHARACTER VARYING(255),
	OPTION_2 CHARACTER VARYING(255),
	OPTION_3 CHARACTER VARYING(255),
	OPTION_4 CHARACTER VARYING(255),
	CORRECT_OPTION INTEGER,
	CONSTRAINT CONSTRAINT_2 PRIMARY KEY (ID)
);
CREATE UNIQUE INDEX PRIMARY_KEY_2 ON PUBLIC.QUIZ (ID);

INSERT INTO PUBLIC.DICTIONARY (ENGLISH_WORD,CROATIAN_WORD) VALUES
	 ('bed','krevet'),
	 ('guitar','gitara'),
	 ('carpet','tepih'),
	 ('fence','ograda');
INSERT INTO PUBLIC.FLASHCARDS (FRONT_TEXT,BACK_TEXT) VALUES
	 ('smeće','trash'),
	 ('miš','mouse'),
	 ('sir','cheese'),
	 ('gospodin','sir');
INSERT INTO PUBLIC.QUIZ (QUESTION,OPTION_1,OPTION_2,OPTION_3,OPTION_4,CORRECT_OPTION) VALUES
	 ('auto','car','bus','train','plane',1),
	 ('boca','headphones','bottle','tissue','shirt',2),
	 ('novčanik','paper','sugar','amplifier','wallet',4),
	 ('ručnik','jeans','window','towel','plate',3);
